fix insufficient storage

diff --git a/.github/workflows/cml.yaml b/.github/workflows/cml.yaml
--- a/.github/workflows/cml.yaml
+++ b/.github/workflows/cml.yaml
@@ -6,10 +6,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-
       - name: Set up CML
         uses: iterative/setup-cml@v1
-
       - name: Deploy runner on AWS
         env:
           REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
@@ -29,7 +27,6 @@ jobs:
     container: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
     steps:
       - uses: actions/checkout@v3
-      
       - name: Install Python and Dependencies
         run: |
           sudo apt-get update
@@ -41,6 +38,17 @@ jobs:
         run: |
           dvc remote modify s3-remote access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --local
           dvc remote modify s3-remote secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --local
+
+      - name: Diagnostics
+        run: |
+          mount | grep -v 'type proc' | grep -v 'type sysfs' | grep -v 'type tmpfs'
+          df -h
+          whoami
+          id
+          sudo touch /test_write_access || echo "Cannot write to root"
+          touch ./test_write_access_local || echo "Cannot write to working directory"
+          sudo chmod 777 /test_write_access
+          chmod 777 ./test_write_access_local
 
       - name: DVC Pull Data
         run: |
@@ -57,7 +65,6 @@ jobs:
           REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           cd unet
-          # Assuming train.py or another script generates a summary.txt
           echo "## Training Summary" >> report.md
           cat summary.txt >> report.md
           cml comment create report.md
